version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: |
          ssh -oStrictHostKeyChecking=no gnosis@178.62.227.183 'mkdir -p src/faucet-server-docker'  
          scp -oStrictHostKeyChecking=no docker-compose.yml .env gnosis@178.62.227.183:src/faucet-server-docker/
          ssh -oStrictHostKeyChecking=no gnosis@178.62.227.183 'docker-compose up'
# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master