version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: 
        name: Create directories if not exists
        command: ssh -oStrictHostKeyChecking=no gnosis@178.62.227.183 bash -c 'mkdir -p src/faucet-server-docker'  

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master