version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run:
        name: Install Linux Packages
        command: apt-get install -y sshpass
      - run: sshpass -p $PASSWORD ssh -oStrictHostKeyChecking=no -v deployer@gnosisfaucet.com "./deploy_faucet_server.sh"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master